// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WinForms.Models
{
    public partial class Department
    {
        public Department()
        {
            Employees = new HashSet<Employee>();
            Projects = new HashSet<Project>();
        }

        [StringLength(50)]
        public string Dname { get; set; }
        [Key]
        public int Dnum { get; set; }
        public int? MGRSSN { get; set; }
        [Column("MGRStart Date", TypeName = "datetime")]
        public DateTime? MGRStart_Date { get; set; }

        [ForeignKey("MGRSSN")]
        [InverseProperty("Departments")]
        public virtual Employee MGRSSNNavigation { get; set; }
        [InverseProperty("DnoNavigation")]
        public virtual ICollection<Employee> Employees { get; set; }
        [InverseProperty("DnumNavigation")]
        public virtual ICollection<Project> Projects { get; set; }
    }
}