// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WinForms.Models
{
    [Table("Dependent")]
    public partial class Dependent
    {
        [Key]
        public int ESSN { get; set; }
        [Key]
        [StringLength(255)]
        public string Dependent_name { get; set; }
        [StringLength(255)]
        public string Sex { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Bdate { get; set; }

        [ForeignKey("ESSN")]
        [InverseProperty("Dependents")]
        public virtual Employee ESSNNavigation { get; set; }
    }
}