// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WinForms.Models
{
    [Table("Employee")]
    public partial class Employee
    {
        public Employee()
        {
            Departments = new HashSet<Department>();
            Dependents = new HashSet<Dependent>();
            InverseSuperssnNavigation = new HashSet<Employee>();
            Works_fors = new HashSet<Works_for>();
        }

        [StringLength(50)]
        public string Fname { get; set; }
        [StringLength(50)]
        public string Lname { get; set; }
        [Key]
        public int SSN { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Bdate { get; set; }
        [StringLength(50)]
        public string Address { get; set; }
        [StringLength(50)]
        public string Sex { get; set; }
        public int? Salary { get; set; }
        public int? Superssn { get; set; }
        public int? Dno { get; set; }

        [ForeignKey("Dno")]
        [InverseProperty("Employees")]
        public virtual Department DnoNavigation { get; set; }
        [ForeignKey("Superssn")]
        [InverseProperty("InverseSuperssnNavigation")]
        public virtual Employee SuperssnNavigation { get; set; }
        [InverseProperty("MGRSSNNavigation")]
        public virtual ICollection<Department> Departments { get; set; }
        [InverseProperty("ESSNNavigation")]
        public virtual ICollection<Dependent> Dependents { get; set; }
        [InverseProperty("SuperssnNavigation")]
        public virtual ICollection<Employee> InverseSuperssnNavigation { get; set; }
        [InverseProperty("ESSnNavigation")]
        public virtual ICollection<Works_for> Works_fors { get; set; }
    }
}