// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF3.Models
{
    public partial class Department
    {
        public Department()
        {
            Employees = new HashSet<Employee>();
            Projects = new HashSet<Project>();
        }

        public string Dname { get; set; }
        public int Dnum { get; set; }
        public int? Mgrssn { get; set; }
        public DateTime? MgrstartDate { get; set; }

        public virtual Employee MgrssnNavigation { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
    }
}