// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF3.Models
{
    public partial class Dependent
    {
        public int Essn { get; set; }
        public string DependentName { get; set; }
        public string Sex { get; set; }
        public DateTime? Bdate { get; set; }

        public virtual Employee EssnNavigation { get; set; }
    }
}