// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF3.Models
{
    public partial class Employee
    {
        public Employee()
        {
            Departments = new HashSet<Department>();
            Dependents = new HashSet<Dependent>();
            InverseSuperssnNavigation = new HashSet<Employee>();
            WorksFors = new HashSet<WorksFor>();
        }

        public string Fname { get; set; }
        public string Lname { get; set; }
        public int Ssn { get; set; }
        public DateTime? Bdate { get; set; }
        public string Address { get; set; }
        public string Sex { get; set; }
        public int? Salary { get; set; }
        public int? Superssn { get; set; }
        public int? Dno { get; set; }

        public virtual Department DnoNavigation { get; set; }
        public virtual Employee SuperssnNavigation { get; set; }
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Dependent> Dependents { get; set; }
        public virtual ICollection<Employee> InverseSuperssnNavigation { get; set; }
        public virtual ICollection<WorksFor> WorksFors { get; set; }
    }
}