// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF3.Models
{
    public partial class Project
    {
        public Project()
        {
            WorksFors = new HashSet<WorksFor>();
        }

        public string Pname { get; set; }
        public int Pnumber { get; set; }
        public string Plocation { get; set; }
        public string City { get; set; }
        public int? Dnum { get; set; }

        public virtual Department DnumNavigation { get; set; }
        public virtual ICollection<WorksFor> WorksFors { get; set; }
    }
}